weights: /content/drive/MyDrive/Yolo7/exp2/weights/epoch_224.pt
cfg: ''
data: dataset.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 300
batch_size: 5
img_size:
- 320
- 320
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: /content/drive/MyDrive/Yolo7
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: 100
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: /content/drive/MyDrive/Yolo7/exp2
total_batch_size: 5
